name: flimm

services:
  php:
    build:
      context: .
      target: dev
      dockerfile: docker/php/Dockerfile
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      SERVER_NAME: ":80"
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
