name: flimm

services:
  app:
    build:
      context: .
      target: dev
      dockerfile: docker/php/Dockerfile
    ports:
      - "80:80"
    env_file: ".env"
    environment:
      SERVER_NAME: ":80"
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
