name: flimm

services:
  php:
    build:
      target: prod
    volumes: !override
      - caddy_data:/data
      - caddy_config:/config
      - db_data:/app/database/sqlite
      - app_storage:/app/storage
    tty: false

volumes:
  db_data:
  app_storage:
